---
- name: "Installing packages"
  apt:
    name: "{{ base_packages }}"
    state: latest
    update_cache: true
  become: true

- name: "Add APT KEY for influxDB"
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  tags: ['apt']
  become: true

- name: "Add repository for influxDB"
  apt_repository:
    repo: deb https://repos.influxdata.com/debian jessie stable
    state: present
  when: ansible_distribution in [ 'Debian', 'Raspbian']
  tags: ['apt']
  become: true

- name: "Add repository for influxDB"
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu/ xenial stable
    state: present
  when: ansible_distribution in [ 'Ubuntu' ]
  tags: ['apt']
  become: true

- name: "Install influxDB"
  apt:
    name: influxdb
    state: present
    update_cache: true
  become: true

- name: "Start influxdb"
  systemd:
    state: started
    name: influxdb
  become: true

- name: "Installing Grafana (for RPi/Omnia)"
  shell: "wget $(wget "https://api.github.com/repos/fg2it/grafana-on-raspberry/releases/latest" -q -O - | grep browser_download_url | grep armhf.deb | head -n 1 | cut -d '"' -f 4) -O grafana.deb"
  when: bc_system == "raspberry" or bc_system == "omnia"

- name: "Installing Grafana (for RPi/Omnia)"
  shell: sudo dpkg -i grafana.deb
  when: bc_system == "raspberry" or bc_system == "omnia"

- name: "Add repository key for Grafana"
  become: true
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present
  when: bc_system == "debian" or bc_system == "ubuntu"

- name: "Add repository for Grafana"
  become: true
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ jessie main
    state: present
  when: bc_system == "deian" or bc_system == "ubuntu"

- name: Installing Grafana
  become: true
  apt:
    name: grafana
    state: present
    update_cache: true
  when: bc_system == "deian" or bc_system == "ubuntu"




- name: Starting grafana-server service
  become: true
  systemd:
    name: grafana-server
    enabled: yes
    state: started